# Generated by Django 3.2.16 on 2023-01-04 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('info', models.TextField()),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'info',
                'verbose_name_plural': 'Infos',
            },
        ),
        migrations.AlterModelOptions(
            name='yangiliklar',
            options={'verbose_name': 'item', 'verbose_name_plural': 'news'},
        ),
    ]
